[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m pytest_operator.plugin:plugin.py:675 Connecting to existing model concierge-microk8s:testing on unspecified cloud
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHSession received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHTunneler received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m integration.high_availability.conftest:conftest.py:57 Deploying mysql-k8s and scaling to 3 units
[32mINFO    [0m juju.model:model.py:2284 Deploying local:mysql-k8s-0
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [allocating] waiting: installing agent
  mysql-k8s/1 [allocating] waiting: installing agent
  mysql-k8s/2 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [executing] maintenance: installing charm software
  mysql-k8s/1 [executing] maintenance: installing charm software
  mysql-k8s/2 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [executing] active: Primary
  mysql-k8s/1 [executing] waiting: waiting to get cluster primary from peers
  mysql-k8s/2 [idle] maintenance: joining the cluster
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [executing] active: Primary
  mysql-k8s/1 [executing] maintenance: joining the cluster
  mysql-k8s/2 [executing] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-k8s/1 [idle] active: 
  mysql-k8s/2 [idle] active: 
[32mINFO    [0m integration.high_availability.conftest:conftest.py:60 Deploying mysql-test-app
[32mINFO    [0m juju.model:model.py:2284 Deploying ch:amd64/jammy/mysql-test-app-82
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-test-app/0 [allocating] waiting: installing agent
[32mINFO    [0m integration.high_availability.conftest:conftest.py:63 Relating mysql-k8s with mysql-test-app
[33mWARNING [0m juju.model:model.py:1666 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-k8s/1 [idle] active: 
  mysql-k8s/2 [idle] active: 
  mysql-test-app/0 [idle] waiting: 
[32mINFO    [0m integration.conftest:conftest.py:30 Getting credentials for the MySQL cluster
[32mINFO    [0m integration.high_availability.test_self_healing_pod:test_self_healing_pod.py:33 Scale mysql application to 1 unit that is active
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s (waiting for exactly 1 units, current : 3)
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s (waiting for exactly 1 units, current : 3)
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
[32mINFO    [0m integration.high_availability.test_self_healing_pod:test_self_healing_pod.py:39 Delete pod for the the mysql unit
[32mINFO    [0m httpx:_client.py:1026 HTTP Request: DELETE https://10.1.0.209:16443/api/v1/namespaces/testing/pods/mysql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.high_availability.test_self_healing_pod:test_self_healing_pod.py:43 Wait for a new pod to be created by k8s
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] maintenance: offline
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
[32mINFO    [0m integration.high_availability.test_self_healing_pod:test_self_healing_pod.py:53 Write data to unit and verify that data was written
[32mINFO    [0m mysql.connector:authentication.py:66 package: mysql.connector.plugins
[32mINFO    [0m mysql.connector:authentication.py:67 plugin_name: caching_sha2_password
[32mINFO    [0m mysql.connector:authentication.py:71 AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.8    unsupported  01:42:39Z

App             Version                  Status  Scale  Charm           Channel      Rev  Address         Exposed  Message
mysql-k8s       8.0.42-0ubuntu0.22.04.2  active      1  mysql-k8s                      0  10.152.183.160  no       
mysql-test-app  0.0.2                    active      1  mysql-test-app  latest/edge   82  10.152.183.117  no       Last written value=560

Unit               Workload  Agent  Address     Ports  Message
mysql-k8s/0*       active    idle   10.1.98.15         Primary
mysql-test-app/0*  active    idle   10.1.98.14         Last written value=560

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

unit-mysql-k8s-0: 01:36:51 ERROR unit.mysql-k8s/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/charm.py", line 1102, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/relations/mysql_provider.py", line 255, in _on_update_status
    self.charm._mysql.update_endpoints(DB_RELATION_NAME)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysql_k8s_helpers.py", line 906, in update_endpoints
    rw_endpoints, ro_endpoints, offline = self.charm.get_cluster_endpoints(relation_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/lib/charms/mysql/v0/mysql.py", line 803, in get_cluster_endpoints
    address = f"{self.get_unit_address(unit_labels[k], relation_name)}:3306"
KeyError: 'mysql-k8s-1.mysql-k8s-endpoints.testing.svc.cluster.local.:3306'
unit-mysql-k8s-0: 01:36:51 ERROR juju.worker.uniter.operation hook "update-status" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-k8s-0: 01:39:53 ERROR unit.mysql-k8s/0.juju-log Cluster upgrade failed, ensure pre-upgrade checks are ran first.

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...