[32mINFO    [0m integration.test_charm:test_charm.py:329 Checking that max_connections is set to 100 on mysql-k8s/0
[32mINFO    [0m integration.test_charm:test_charm.py:329 Checking that innodb_buffer_pool_size is set to 20971520 on mysql-k8s/0
[32mINFO    [0m integration.test_charm:test_charm.py:329 Checking that innodb_buffer_pool_chunk_size is set to 1048576 on mysql-k8s/0
[32mINFO    [0m integration.test_charm:test_charm.py:329 Checking that group_replication_message_cache_size is set to 134217728 on mysql-k8s/0
[32mINFO    [0m integration.test_charm:test_charm.py:329 Checking that max_connections is set to 100 on mysql-k8s/1
[32mINFO    [0m integration.test_charm:test_charm.py:329 Checking that innodb_buffer_pool_size is set to 20971520 on mysql-k8s/1
[32mINFO    [0m integration.test_charm:test_charm.py:329 Checking that innodb_buffer_pool_chunk_size is set to 1048576 on mysql-k8s/1
[32mINFO    [0m integration.test_charm:test_charm.py:329 Checking that group_replication_message_cache_size is set to 134217728 on mysql-k8s/1
[32mINFO    [0m integration.test_charm:test_charm.py:329 Checking that max_connections is set to 100 on mysql-k8s/2
[32mINFO    [0m integration.test_charm:test_charm.py:329 Checking that innodb_buffer_pool_size is set to 20971520 on mysql-k8s/2
[32mINFO    [0m integration.test_charm:test_charm.py:329 Checking that innodb_buffer_pool_chunk_size is set to 1048576 on mysql-k8s/2
[32mINFO    [0m integration.test_charm:test_charm.py:329 Checking that group_replication_message_cache_size is set to 134217728 on mysql-k8s/2
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.5    unsupported  01:40:52Z

App        Version  Status  Scale  Charm      Channel  Rev  Address         Exposed  Message
mysql-k8s           active      3  mysql-k8s             0  10.152.183.130  no       

Unit          Workload  Agent  Address       Ports  Message
mysql-k8s/0*  active    idle   10.1.222.139         Primary
mysql-k8s/1   active    idle   10.1.222.147         
mysql-k8s/2   active    idle   10.1.222.146         

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

unit-mysql-k8s-2: 01:34:59 ERROR unit.mysql-k8s/2.juju-log restart:0: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/model.py", line 3187, in _run
    result = subprocess.run(args, **kwargs)  # type: ignore
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-mysql-k8s-2/secret-get', '--label', 'database-peers.mysql-k8s.app', '--format=json')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/./src/charm.py", line 888, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 549, in main
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 432, in __init__
    self.charm = self._make_charm(self.framework, self.dispatcher)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 435, in _make_charm
    charm = self._charm_class(framework)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 441, in wrap_init
    original_init(self, framework, *args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/./src/charm.py", line 179, in __init__
    self.log_rotate_manager.start_log_rotate_manager()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/log_rotate_manager.py", line 41, in start_log_rotate_manager
    or not self.charm.unit_initialized
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/mysql.py", line 642, in unit_initialized
    return self._mysql.cluster_metadata_exists(self.get_unit_address(self.unit))
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/./src/charm.py", line 202, in _mysql
    self.get_secret("app", ROOT_PASSWORD_KEY),  # pyright: ignore [reportArgumentType]
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/mysql.py", line 749, in get_secret
    if not (value := self.peer_relation_data(scope).fetch_my_relation_field(peers.id, key)):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1393, in fetch_my_relation_field
    if relation_data := self.fetch_my_relation_data([relation_id], [field], relation_name):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1382, in fetch_my_relation_data
    data[relation.id] = self._fetch_my_specific_relation_data(relation, fields)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 532, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2329, in _fetch_my_specific_relation_data
    self.component, self.secret_fields, relation, fields
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1966, in secret_fields
    self.static_secret_fields if self.static_secret_fields else self.current_secret_fields
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1985, in current_secret_fields
    if content := self._get_group_secret_contents(relation, group):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2316, in _get_group_secret_contents
    result = super()._get_group_secret_contents(relation, group, secret_fields)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1119, in _get_group_secret_contents
    if (secret := self._get_relation_secret(relation.id, group)) and (
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 504, in wrapper
    return f(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 2303, in _get_relation_secret
    return self.secrets.get(
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 808, in get
    if secret.meta:
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 638, in meta
    self._secret_meta = self._model.get_secret(label=self.label)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/model.py", line 291, in get_secret
    content = self._backend.secret_get(id=id, label=label)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/model.py", line 3552, in secret_get
    result = self._run('secret-get', *args, return_output=True, use_json=True)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/model.py", line 3189, in _run
    raise ModelError(e.stderr) from e
ops.model.ModelError: ERROR cannot ensure service account "unit-mysql-k8s-2": rpc error: code = Unknown desc = exec (try: 500): database is locked

unit-mysql-k8s-2: 01:34:59 ERROR juju.worker.uniter.operation hook "restart-relation-joined" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...