[32mINFO    [0m pytest_operator.plugin:plugin.py:675 Connecting to existing model concierge-microk8s:testing on unspecified cloud
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m integration.high_availability.conftest:conftest.py:57 Deploying mysql-k8s and scaling to 3 units
[32mINFO    [0m juju.model:model.py:2284 Deploying local:mysql-k8s-0
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [allocating] waiting: installing agent
  mysql-k8s/1 [allocating] waiting: installing agent
  mysql-k8s/2 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [executing] maintenance: installing charm software
  mysql-k8s/1 [executing] maintenance: installing charm software
  mysql-k8s/2 [executing] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [executing] active: Primary
  mysql-k8s/1 [idle] waiting: waiting to get cluster primary from peers
  mysql-k8s/2 [executing] waiting: waiting to get cluster primary from peers
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [executing] active: Primary
  mysql-k8s/1 [executing] active: 
  mysql-k8s/2 [executing] maintenance: joining the cluster
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-k8s/1 [idle] active: 
  mysql-k8s/2 [idle] active: 
[32mINFO    [0m integration.high_availability.conftest:conftest.py:60 Deploying mysql-test-app
[32mINFO    [0m juju.model:model.py:2284 Deploying ch:amd64/jammy/mysql-test-app-73
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-test-app/0 [allocating] waiting: installing agent
[32mINFO    [0m integration.high_availability.conftest:conftest.py:63 Relating mysql-k8s with mysql-test-app
[33mWARNING [0m juju.model:model.py:1666 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-k8s/1 [idle] active: 
  mysql-k8s/2 [idle] active: 
  mysql-test-app/0 [idle] waiting: 
[32mINFO    [0m integration.conftest:conftest.py:30 Getting credentials for the MySQL cluster
[32mINFO    [0m mysql.connector:authentication.py:66 package: mysql.connector.plugins
[32mINFO    [0m mysql.connector:authentication.py:67 plugin_name: caching_sha2_password
[32mINFO    [0m mysql.connector:authentication.py:71 AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s (waiting for exactly 4 units, current : 3)
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [executing] active: Primary
  mysql-k8s/1 [idle] active: 
  mysql-k8s/2 [executing] active: 
  mysql-k8s/3 [executing] maintenance: Initialising mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-k8s/1 [idle] active: 
  mysql-k8s/2 [idle] active: 
  mysql-k8s/3 [idle] maintenance: joining the cluster
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: Primary
  mysql-k8s/1 [idle] active: 
  mysql-k8s/2 [idle] active: 
  mysql-k8s/3 [executing] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/3 [idle] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s (waiting for exactly 3 units, current : 4)
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s (waiting for exactly 3 units, current : 4)
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.4    unsupported  01:35:55Z

App             Version                  Status  Scale  Charm           Channel      Rev  Address         Exposed  Message
mysql-k8s       8.0.41-0ubuntu0.22.04.1  active      3  mysql-k8s                      0  10.152.183.250  no       
mysql-test-app  0.0.2                    active      1  mysql-test-app  latest/edge   73  10.152.183.33   no       Last written value=693

Unit               Workload  Agent  Address      Ports  Message
mysql-k8s/0*       active    idle   10.1.154.75         Primary
mysql-k8s/1        active    idle   10.1.154.76         
mysql-k8s/2        active    idle   10.1.154.77         
mysql-test-app/0*  active    idle   10.1.154.78         Last written value=693

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

unit-mysql-k8s-1: 01:30:09 ERROR unit.mysql-k8s/1.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/websocket/_socket.py", line 118, in recv
    bytes_ = _recv()
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/websocket/_socket.py", line 97, in _recv
    return sock.recv(bufsize)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 2890, in exec
    control_ws = self._connect_websocket(task_id, 'control')
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 2978, in _connect_websocket
    ws.connect(url, socket=sock)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/websocket/_core.py", line 261, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/websocket/_handshake.py", line 65, in handshake
    status, resp = _get_resp_headers(sock)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/websocket/_handshake.py", line 141, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/websocket/_http.py", line 351, in read_headers
    line = recv_line(sock)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/websocket/_socket.py", line 140, in recv_line
    c = recv(sock, 1)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/websocket/_socket.py", line 120, in recv
    raise WebSocketTimeoutException("Connection timed out")
websocket._exceptions.WebSocketTimeoutException: Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/src/mysql_k8s_helpers.py", line 722, in _run_mysqlsh_script
    process = self.container.exec(cmd, stdin=password)
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 2872, in exec
    return self._pebble.exec(
  File "/var/lib/juju/agents/unit-mysql-k8s-1/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 2899, in exec
    raise ChangeError(change.err, change) from e
ops.pebble.ChangeError: cannot perform the following tasks:
- Execute command "/usr/bin/mysqlsh" (exec 14: timeout waiting for websocket connections: context deadline exceeded)
----- Logs from task 0 -----
2025-03-27T01:30:09Z ERROR exec 14: timeout waiting for websocket connections: context deadline exceeded
-----
unit-mysql-k8s-1: 01:30:09 ERROR unit.mysql-k8s/1.juju-log Failed to get value for variable='plugin_dir'
unit-mysql-k8s-0: 01:30:37 ERROR unit.mysql-k8s/0.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-0: 01:30:39 ERROR unit.mysql-k8s/0.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-0: 01:30:41 ERROR unit.mysql-k8s/0.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:32:58 ERROR unit.mysql-k8s/2.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:33:00 ERROR unit.mysql-k8s/2.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-0: 01:33:01 ERROR unit.mysql-k8s/0.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:33:02 ERROR unit.mysql-k8s/2.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-0: 01:33:03 ERROR unit.mysql-k8s/0.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:33:05 ERROR unit.mysql-k8s/2.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:33:07 ERROR unit.mysql-k8s/2.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-2: 01:33:09 ERROR unit.mysql-k8s/2.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:33:58 ERROR unit.mysql-k8s/3.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:34:00 ERROR unit.mysql-k8s/3.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:34:02 ERROR unit.mysql-k8s/3.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:34:13 ERROR unit.mysql-k8s/3.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:34:15 ERROR unit.mysql-k8s/3.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:34:17 ERROR unit.mysql-k8s/3.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:34:19 ERROR unit.mysql-k8s/3.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:34:21 ERROR unit.mysql-k8s/3.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again
unit-mysql-k8s-3: 01:34:23 ERROR unit.mysql-k8s/3.juju-log upgrade:1: get_unit_address: unit DNS domain name is not fully propagated yet, trying again

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...