[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m pytest_operator.plugin:plugin.py:675 Connecting to existing model concierge-microk8s:testing on unspecified cloud
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHSession received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHTunneler received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m integration.high_availability.conftest:conftest.py:57 Deploying mysql-k8s and scaling to 3 units
[32mINFO    [0m juju.model:model.py:2284 Deploying local:mysql-k8s-0
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [allocating] waiting: installing agent
  mysql-k8s/1 [allocating] waiting: installing agent
  mysql-k8s/2 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] maintenance: installing charm software
  mysql-k8s/1 [idle] maintenance: installing charm software
  mysql-k8s/2 [idle] maintenance: installing charm software
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [executing] waiting: waiting to get cluster primary from peers
  mysql-k8s/1 [executing] waiting: waiting to get cluster primary from peers
  mysql-k8s/2 [executing] active: Primary
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [executing] maintenance: joining the cluster
  mysql-k8s/1 [executing] active: 
  mysql-k8s/2 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/2 [idle] active: Primary
[32mINFO    [0m integration.high_availability.conftest:conftest.py:60 Deploying mysql-test-app
[32mINFO    [0m juju.model:model.py:2284 Deploying ch:amd64/jammy/mysql-test-app-85
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-test-app/0 [allocating] waiting: installing agent
[32mINFO    [0m integration.high_availability.conftest:conftest.py:63 Relating mysql-k8s with mysql-test-app
[33mWARNING [0m juju.model:model.py:1666 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/0 [idle] active: 
  mysql-k8s/1 [idle] active: 
  mysql-k8s/2 [idle] active: Primary
  mysql-test-app/0 [idle] waiting: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-k8s/2 [idle] active: 
[32mINFO    [0m integration.high_availability.conftest:conftest.py:27 Clearing continuous writes
[32mINFO    [0m integration.high_availability.conftest:conftest.py:29 Starting continuous writes
[32mINFO    [0m integration.conftest:conftest.py:31 Getting credentials for the MySQL cluster
[32mINFO    [0m juju.model:model.py:2284 Deploying local:mysql-k8s-1
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  another-mysql/0 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  another-mysql/0 [executing] maintenance: Initialising mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  another-mysql/0 [idle] active: Primary
[32mINFO    [0m integration.high_availability.conftest:conftest.py:34 Clearing continuous writes
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.9    unsupported  02:17:26Z

App             Version                  Status  Scale  Charm           Channel      Rev  Address         Exposed  Message
another-mysql   8.0.42-0ubuntu0.22.04.2  active    1/0  mysql-k8s                      1  10.152.183.129  no       
mysql-k8s       8.0.42-0ubuntu0.22.04.2  active      3  mysql-k8s                      0  10.152.183.70   no       
mysql-test-app  0.0.2                    active      1  mysql-test-app  latest/edge   85  10.152.183.241  no       Last written value=214

Unit               Workload  Agent      Address      Ports  Message
another-mysql/0*   active    executing  10.1.242.80         Primary
mysql-k8s/0        active    idle       10.1.242.75         
mysql-k8s/1        active    idle       10.1.242.77         
mysql-k8s/2*       active    idle       10.1.242.76         Primary
mysql-test-app/0*  active    idle       10.1.242.78         Last written value=214

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

unit-mysql-k8s-2: 02:14:28 ERROR unit.mysql-k8s/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/charm.py", line 1123, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/relations/mysql_provider.py", line 252, in _on_update_status
    self.charm._mysql.update_endpoints(DB_RELATION_NAME)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/src/mysql_k8s_helpers.py", line 896, in update_endpoints
    rw_endpoints, ro_endpoints, offline = self.charm.get_cluster_endpoints(relation_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/mysql/v0/mysql.py", line 903, in get_cluster_endpoints
    address = f"{self.get_unit_address(unit_labels[k], relation_name)}:3306"
KeyError: 'mysql-k8s-0.mysql-k8s-endpoints.testing.svc.cluster.local.:3306'
unit-mysql-k8s-2: 02:14:28 ERROR juju.worker.uniter.operation hook "update-status" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...