[32mINFO    [0m integration.high_availability.conftest:conftest.py:27 Clearing continuous writes
[32mINFO    [0m integration.high_availability.conftest:conftest.py:29 Starting continuous writes
[32mINFO    [0m integration.high_availability.test_async_replication:test_async_replication.py:320 Stopping continuous writes after 5s
[32mINFO    [0m integration.high_availability.test_async_replication:test_async_replication.py:328 Remove async relation
[32mINFO    [0m integration.high_availability.test_async_replication:test_async_replication.py:334 waiting for units to be blocked
[32mINFO    [0m integration.high_availability.test_async_replication:test_async_replication.py:340 Waiting for the applications to settle
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/0 [executing] blocked: Standalone read-only unit.
  db2/1 [executing] blocked: Standalone read-only unit.
  db2/2 [executing] blocked: Standalone read-only unit.
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db1/0 [idle] active: 
  db1/1 [executing] maintenance: Removing replica cluster
  db1/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/0 [idle] blocked: Standalone read-only unit.
  db2/1 [idle] blocked: Standalone read-only unit.
  db2/2 [executing] blocked: Standalone read-only unit.
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/2 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/2 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/2 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/2 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/2 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/2 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/2 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/2 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/2 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/2 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/2 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/2 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/2 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/2 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/2 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/0 [executing] blocked: Standalone read-only unit.
  db2/1 [executing] blocked: Standalone read-only unit.
  db2/2 [executing] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/2 [idle] maintenance: Starting mysqld
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  db2/0 [executing] blocked: Standalone read-only unit.
  db2/1 [executing] blocked: Standalone read-only unit.
  db2/2 [executing] maintenance: Starting mysqld
[32mINFO    [0m integration.high_availability.conftest:conftest.py:34 Clearing continuous writes
[32mINFO    [0m integration.high_availability.test_async_replication:test_async_replication.py:67 Destroying second model
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.2    unsupported  01:53:27Z

App               Version                  Status  Scale  Charm             Channel      Rev  Address         Exposed  Message
db1               8.0.41-0ubuntu0.22.04.1  active      3  mysql-k8s                        0  10.152.183.173  no       
mysql-router-k8s  8.0.41-0ubuntu0.22.04.1  active      1  mysql-router-k8s  8.0/edge     593  10.152.183.178  no       
mysql-test-app    0.0.2                    active      1  mysql-test-app    latest/edge   69  10.152.183.59   no       

Unit                 Workload  Agent  Address     Ports  Message
db1/0                active    idle   10.1.16.76         
db1/1*               active    idle   10.1.16.78         Primary
db1/2                active    idle   10.1.16.77         
mysql-router-k8s/0*  active    idle   10.1.16.85         
mysql-test-app/0*    active    idle   10.1.16.86         

Offer  Application  Charm      Rev  Connected  Endpoint           Interface    Role
db1    db1          mysql-k8s  0    0/0        replication-offer  mysql_async  provider

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

unit-db1-2: 01:38:02 ERROR unit.db1/2.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-db1-2/charm/src/mysql_k8s_helpers.py", line 675, in _run_mysqlsh_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-db1-2/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['timeout', '30', '/usr/bin/mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@db1-2.db1-endpoints.testing.svc.cluster.local:33062', '--python', '--verbose=0', '-c', "shell.options.set('useWizards', False)\nprint('###')\ncluster = dba.get_cluster('lima')\nprint(cluster.status({'extended': False}))"], stdout="\x1b[1mPlease provide the password for 'serverconfig@db1-2.db1-endpoints.testing.svc.cluster.local:33062': \x1b[0m###\n", stderr='Cannot set LC_ALL to locale en_US.UTF-8: No such file or directory\n\x1b[33mWARNING: \x1b[0mError connecting to Cluster: RuntimeError: Could not open connection to \'db2-0.db2-endpoints.testing-other.svc.cluster.local:3306\': The provided URI uses the X protocol, which is not supported by this command.\nTraceback (most recent call last):\n  File "<string>", line 3, in <module>\nRuntimeError: Dba.get_cluster: Could not open connection to \'db2-0.db2-endpoints.testing-other.svc.cluster.local:3306\': The provided URI uses the X protocol, which is not supported by this command.\n\n'
unit-db1-2: 01:38:02 ERROR unit.db1/2.juju-log Failed to get cluster status for lima
unit-db1-2: 01:38:02 ERROR unit.db1/2.juju-log Failed to get cluster endpoints
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-db1-2/charm/src/mysql_k8s_helpers.py", line 856, in update_endpoints
    rw_endpoints, ro_endpoints, offline = self.get_cluster_endpoints(get_ips=False)
  File "/var/lib/juju/agents/unit-db1-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-db1-2/charm/lib/charms/mysql/v0/mysql.py", line 2097, in get_cluster_endpoints
    raise MySQLGetClusterEndpointsError("Failed to get endpoints from cluster status")
charms.mysql.v0.mysql.MySQLGetClusterEndpointsError: Failed to get endpoints from cluster status
unit-db1-0: 01:38:02 ERROR unit.db1/0.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-db1-0/charm/src/mysql_k8s_helpers.py", line 675, in _run_mysqlsh_script
    stdout, _ = process.wait_output()
  File "/var/lib/juju/agents/unit-db1-0/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 1771, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['timeout', '30', '/usr/bin/mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@db1-0.db1-endpoints.testing.svc.cluster.local:33062', '--python', '--verbose=0', '-c', "shell.options.set('useWizards', False)\nprint('###')\ncluster = dba.get_cluster('lima')\nprint(cluster.status({'extended': False}))"], stdout="\x1b[1mPlease provide the password for 'serverconfig@db1-0.db1-endpoints.testing.svc.cluster.local:33062': \x1b[0m###\n", stderr='Cannot set LC_ALL to locale en_US.UTF-8: No such file or directory\n\x1b[33mWARNING: \x1b[0mError connecting to Cluster: RuntimeError: Could not open connection to \'db2-0.db2-endpoints.testing-other.svc.cluster.local:3306\': The provided URI uses the X protocol, which is not supported by this command.\nTraceback (most recent call last):\n  File "<string>", line 3, in <module>\nRuntimeError: Dba.get_cluster: Could not open connection to \'db2-0.db2-endpoints.testing-other.svc.cluster.local:3306\': The provided URI uses the X protocol, which is not supported by this command.\n\n'
unit-db1-0: 01:38:02 ERROR unit.db1/0.juju-log Failed to get cluster status for lima
unit-db1-0: 01:38:02 ERROR unit.db1/0.juju-log Failed to get cluster endpoints
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-db1-0/charm/src/mysql_k8s_helpers.py", line 856, in update_endpoints
    rw_endpoints, ro_endpoints, offline = self.get_cluster_endpoints(get_ips=False)
  File "/var/lib/juju/agents/unit-db1-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-db1-0/charm/lib/charms/mysql/v0/mysql.py", line 2097, in get_cluster_endpoints
    raise MySQLGetClusterEndpointsError("Failed to get endpoints from cluster status")
charms.mysql.v0.mysql.MySQLGetClusterEndpointsError: Failed to get endpoints from cluster status
unit-db1-0: 01:43:50 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "27ff97d7-7247-4e12-805d-6687b991aa3d:r#3#remote-789e2a616ba44e1883972eea78c58ff0": settings 27ff97d7-7247-4e12-805d-6687b991aa3d:r#3#remote-789e2a616ba44e1883972eea78c58ff0 not found (not found)

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...