[32mINFO    [0m httpx:_client.py:1013 HTTP Request: DELETE https://10.1.0.49:16443/api/v1/namespaces/test/pods/mysql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-k8s/0 [idle] active: 
  mysql-k8s/1 [executing] maintenance: 
  mysql-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-k8s/0 [idle] active: 
  mysql-k8s/1 [idle] maintenance: offline
  mysql-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-k8s/0 [idle] active: 
  mysql-k8s/1 [idle] maintenance: offline
  mysql-k8s/2 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql-k8s/0 [idle] active: 
  mysql-k8s/1 [idle] active: 
  mysql-k8s/2 [idle] active: Primary
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.1.7    unsupported  01:38:46Z

App             Version                  Status  Scale  Charm           Channel      Rev  Address         Exposed  Message
mysql-k8s       8.0.35-0ubuntu0.22.04.1  active      3  mysql-k8s                      0  10.152.183.142  no       
mysql-test-app  0.0.2                    active      1  mysql-test-app  latest/edge   29  10.152.183.121  no       

Unit               Workload  Agent  Address       Ports  Message
mysql-k8s/0*       active    idle   10.1.131.204         
mysql-k8s/1        active    idle   10.1.131.211         
mysql-k8s/2        active    idle   10.1.131.203         Primary
mysql-test-app/0*  active    idle   10.1.131.206         

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

unit-mysql-k8s-1: 01:35:40 ERROR unit.mysql-k8s/1.juju-log Cluster upgrade failed, ensure pre-upgrade checks are ran first.
unit-mysql-k8s-1: 01:35:48 ERROR unit.mysql-k8s/1.juju-log database-peers:1: Failed to get cluster status for test_cluster

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...