[32mINFO    [0m integration.test_tls:test_tls.py:211 Removing relation
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.4    unsupported  01:33:33Z

App                       Version                  Status   Scale  Charm                     Channel        Rev  Address         Exposed  Message
mysql-k8s                 8.0.41-0ubuntu0.22.04.1  waiting      3  mysql-k8s                                  0  10.152.183.231  no       installing agent
self-signed-certificates                           active       1  self-signed-certificates  latest/stable  264  10.152.183.137  no       

Unit                         Workload     Agent  Address     Ports  Message
mysql-k8s/0                  active       idle   10.1.91.75         
mysql-k8s/1*                 active       idle   10.1.91.76         
mysql-k8s/2                  maintenance  idle   10.1.91.77         Starting mysqld
self-signed-certificates/0*  active       idle   10.1.91.78         

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

unit-mysql-k8s-0: 01:32:29 ERROR unit.mysql-k8s/0.juju-log certificates:3: An unknown certificate expiring.
unit-mysql-k8s-1: 01:32:32 ERROR unit.mysql-k8s/1.juju-log certificates:3: An unknown certificate expiring.
unit-mysql-k8s-2: 01:32:34 ERROR unit.mysql-k8s/2.juju-log certificates:3: An unknown certificate expiring.
unit-mysql-k8s-0: 01:32:35 ERROR unit.mysql-k8s/0.juju-log certificates:3: An unknown certificate expiring.
unit-mysql-k8s-1: 01:32:37 ERROR unit.mysql-k8s/1.juju-log certificates:3: An unknown certificate expiring.
unit-mysql-k8s-2: 01:33:08 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "9f9f8818-ff2b-461f-8ebb-709a6830b2b3:r#3#self-signed-certificates": settings 9f9f8818-ff2b-461f-8ebb-709a6830b2b3:r#3#self-signed-certificates not found (not found)

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...